

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
mybatis:
    type-aliases-package: com.pavilion.model
logging:
  file:
    #path:
    name: D:\\log\\log.log
  level:
    root: error